name: Deploy to Amazon ECS

on:
  workflow_call:
    inputs:
      cluster:
        type: string
        required: true
      service:
        type: string
        required: true
      image:
        type: string
        required: true
      task_definition_json:
        type: string
        description: Path to task defintion (e.g. .aws/task_definition.json)
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@97587c9d45a4930bf0e3da8dd2feb2a463cf4a3a
        with:
          task-definition: ${{ inputs.task_definition_json }}
          container-name: ${{ inputs.service }}
          image: ${{ inputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@de0132cf8cdedb79975c6d42b77eb7ea193cf28e
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: "${{ inputs.service }}-service"
          cluster: ${{ inputs.cluster }}
          wait-for-service-stability: true

