name: Tag and Release

on:
  workflow_call:
    inputs:
      bump:
        type: string
        description: Select the version
        required: true
    secrets:
      PAT:
        required: true

env:
  STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
  S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
  S3_BUCKET_REGION:  ${{secrets.S3_BUCKET_REGION}}
  S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
  S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}

  # workflows that call this workflow, will need to use the dispatch below
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Select the version
        required: true
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: next_version
        uses: zwaldowski/semver-release-action@a2f4b5e15e4c1c3ff78524693b9c3c52665526ff
        with:
          prefix: v
          bump: ${{ github.event.inputs.bump }}
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.next_version.outputs.version_tag }}
